// Export builders: SRT captions, timeline JSON bundle, and a Remotion
// composition (source code) so the same timeline can be rendered to a
// production-grade MP4 on any machine with Remotion installed.

import { cueGroups, estimateDuration } from '@/lib/subtitles'
import type { Project, Scene } from '@/lib/types'

function sceneDuration(scene: Scene): number {
  return scene.audioDuration ?? scene.subtitles?.duration ?? estimateDuration(scene.narration)
}

export function totalDuration(scenes: Scene[]): number {
  return scenes.reduce((acc, s) => acc + sceneDuration(s), 0)
}

export function sceneStarts(scenes: Scene[]): number[] {
  const starts: number[] = []
  let acc = 0
  for (const s of scenes) {
    starts.push(acc)
    acc += sceneDuration(s)
  }
  return starts
}

function fmtSrtTime(t: number): string {
  const ms = Math.max(0, Math.round(t * 1000))
  const h = Math.floor(ms / 3600000)
  const m = Math.floor((ms % 3600000) / 60000)
  const s = Math.floor((ms % 60000) / 1000)
  const milli = ms % 1000
  const pad = (n: number, len = 2) => String(n).padStart(len, '0')
  return `${pad(h)}:${pad(m)}:${pad(s)},${pad(milli, 3)}`
}

export function buildSrt(project: Project): string {
  const scenes = project.scenes.filter((s) => s.audioUrl || s.imageUrl)
  const starts = sceneStarts(scenes)
  const cues: { start: number; end: number; text: string }[] = []

  scenes.forEach((scene, i) => {
    const words = scene.subtitles?.words ?? []
    if (words.length === 0) return
    const sceneStart = starts[i]
    const sceneDur = sceneDuration(scene)
    for (const cue of cueGroups(words, 5)) {
      const start = sceneStart + cue[0].s
      const end = sceneStart + Math.min(cue[cue.length - 1].e + 0.15, sceneDur)
      cues.push({ start, end, text: cue.map((w) => w.w).join(' ') })
    }
  })

  if (cues.length === 0) return ''

  return (
    cues
      .map((cue, i) => {
        return `${i + 1}\n${fmtSrtTime(cue.start)} --> ${fmtSrtTime(cue.end)}\n${cue.text}\n`
      })
      .join('\n') + '\n'
  )
}

export function buildTimelineJson(project: Project): string {
  const scenes = project.scenes.filter((s) => s.audioUrl || s.imageUrl)
  const starts = sceneStarts(scenes)
  return JSON.stringify(
    {
      generator: 'NahaLabs Content OS — Video Factory',
      exportedAt: new Date().toISOString(),
      project: {
        id: project.id,
        title: project.title,
        topic: project.topic,
        mode: project.mode,
        platform: project.platform,
        style: project.style,
        voice: project.voice,
        durationTarget: project.durationTarget,
        script: project.script,
      },
      totalDuration: totalDuration(scenes),
      scenes: scenes.map((scene, i) => ({
        index: scene.position,
        start: starts[i],
        duration: sceneDuration(scene),
        narration: scene.narration,
        onScreenText: scene.onScreenText,
        visualPrompt: scene.visualPrompt,
        imageUrl: scene.imageUrl,
        audioUrl: scene.audioUrl,
        words: scene.subtitles?.words ?? [],
      })),
    },
    null,
    2
  )
}

/**
 * Emits a self-contained Remotion composition for this timeline.
 * The generated code deliberately avoids template literals so it stays
 * readable and safe to embed via JSON.stringify.
 */
export function buildRemotionTsx(project: Project): string {
  const scenes = project.scenes.filter((s) => s.audioUrl || s.imageUrl)
  const starts = sceneStarts(scenes)
  const slug = slugify(project.title || 'video')

  const data = scenes.map((scene, i) => ({
    start: starts[i],
    duration: sceneDuration(scene),
    img: scene.imageUrl,
    audio: scene.audioUrl,
    text: scene.onScreenText ?? '',
    cues: cueGroups(scene.subtitles?.words ?? [], 5).map((cue) => ({
      s: cue[0].s,
      e: cue[cue.length - 1].e + 0.15,
      text: cue.map((w) => w.w).join(' '),
    })),
  }))

  const fps = 30
  const totalFrames = Math.max(1, Math.ceil(totalDuration(scenes) * fps))

  const lines: string[] = []
  lines.push('// ' + project.title + ' — Remotion composition export')
  lines.push('// Generated by NahaLabs Content OS — Video Factory')
  lines.push('//')
  lines.push('// How to render this into a real MP4 (on any machine with Node/Bun):')
  lines.push('//   1. bunx create-video@latest --blank ' + slug)
  lines.push('//   2. Copy this file into src/' + slug + '.tsx and register it in Root.tsx')
  lines.push('//   3. Download the timeline JSON export, place the image/audio files it')
  lines.push('//      references under public/ and update the img/audio paths below')
  lines.push('//      (they currently point at the Video Factory app URLs).')
  lines.push('//   4. bunx remotion render ' + slug + ' out/' + slug + '.mp4')
  lines.push('//')
  lines.push('// The timeline below is data — the same "video as code" idea as HyperFrames')
  lines.push('// and the OpenMontage/HyperFrames render targets: edit scenes, re-render.')
  lines.push('')
  lines.push("import { AbsoluteFill, Audio, Img, Sequence, interpolate, useCurrentFrame, useVideoConfig } from 'remotion'")
  lines.push('')
  lines.push('const FPS = ' + fps + ';')
  lines.push('const SCENES = ' + JSON.stringify(data, null, 2) + ' as const;')
  lines.push('')
  lines.push('export const ' + toPascalCase(slug) + ' = () => {')
  lines.push('  return (')
  lines.push('    <AbsoluteFill style={{ backgroundColor: "#0a0a0a" }}>')
  lines.push('      {SCENES.map((scene, i) => (')
  lines.push('        <Sequence key={i} from={Math.round(scene.start * FPS)} durationInFrames={Math.round(scene.duration * FPS)}>')
  lines.push('          <Scene scene={scene} index={i} />')
  lines.push('        </Sequence>')
  lines.push('      ))}')
  lines.push('    </AbsoluteFill>')
  lines.push('  );')
  lines.push('};')
  lines.push('')
  lines.push('const Scene = ({ scene, index }: { scene: (typeof SCENES)[number]; index: number }) => {')
  lines.push('  const frame = useCurrentFrame();')
  lines.push('  const { durationInFrames } = useVideoConfig();')
  lines.push('  const progress = frame / Math.max(1, durationInFrames);')
  lines.push('  // Ken Burns: slow zoom, alternating pan direction')
  lines.push('  const scale = interpolate(progress, [0, 1], [1.06, 1.18]);')
  lines.push('  const panX = interpolate(progress, [0, 1], index % 2 === 0 ? [-20, 20] : [20, -20]);')
  lines.push('  const activeCue = scene.cues.find((c) => frame / FPS >= c.s && frame / FPS <= c.e);')
  lines.push('  return (')
  lines.push('    <AbsoluteFill>')
  lines.push('      <Img')
  lines.push('        src={scene.img}')
  lines.push('        style={{ position: "absolute", width: "100%", height: "100%", objectFit: "cover", transform: "scale(" + scale + ") translateX(" + panX + "px)" }}')
  lines.push('      />')
  lines.push('      {scene.audio ? <Audio src={scene.audio} /> : null}')
  lines.push('      {scene.text ? (')
  lines.push('        <div style={{ position: "absolute", top: "8%", left: "6%", right: "6%", fontSize: 64, fontWeight: 800, color: "#fff", textShadow: "0 4px 24px rgba(0,0,0,0.8)", fontFamily: "sans-serif" }}>')
  lines.push('          {scene.text}')
  lines.push('        </div>')
  lines.push('      ) : null}')
  lines.push('      {activeCue ? (')
  lines.push('        <div style={{ position: "absolute", bottom: "12%", left: "6%", right: "6%", fontSize: 52, fontWeight: 700, color: "#f5f5f5", textShadow: "0 2px 12px rgba(0,0,0,0.9)", fontFamily: "sans-serif", textAlign: "center" }}>')
  lines.push('          {activeCue.text}')
  lines.push('        </div>')
  lines.push('      ) : null}')
  lines.push('    </AbsoluteFill>')
  lines.push('  );')
  lines.push('};')
  lines.push('')
  return lines.join('\n')
}

function slugify(text: string): string {
  return (
    text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 48) || 'video'
  )
}

function toPascalCase(slug: string): string {
  const parts = slug.split('-').filter(Boolean)
  if (parts.length === 0) return 'MyVideo'
  return parts.map((p) => p[0].toUpperCase() + p.slice(1)).join('')
}
